# Generated by Django 4.0 on 2021-12-25 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TagModel',
            new_name='PostTagModel',
        ),
    ]
