# Generated by Django 4.0 on 2022-01-15 15:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0011_productmodel_real_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='izb',
            field=models.ManyToManyField(related_name='izb', to=settings.AUTH_USER_MODEL),
        ),
    ]
