# Generated by Django 4.0 on 2022-01-17 14:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0012_productmodel_izb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='izb',
            field=models.ManyToManyField(related_name='izb', to=settings.AUTH_USER_MODEL, verbose_name='wishlist'),
        ),
    ]
